// Generated by UblXml2CSharp
using System.Xml;
using UblLarsen.Ubl2;
using UblLarsen.Ubl2.Cac;
using UblLarsen.Ubl2.Ext;
using UblLarsen.Ubl2.Udt;

namespace UblLarsen.Test.UblClass
{
    internal class MyTransportationStatus
    {
        private static XmlElement GetElement(string xml)
        {
            XmlDocument doc = new XmlDocument();
            doc.LoadXml(xml);
            return doc.DocumentElement;
        }

        public static TransportationStatusType Create()
        {
            var doc = new TransportationStatusType
            {
                UBLExtensions = new UBLExtensionType[]
                {
                    new UBLExtensionType
                    {
                        // Manually added for testing.
                        ExtensionContent = GetElement(@"        <mec:Additional xmlns:mec=""urn:X-MyCompany:Extension"" 
                        xmlns:cac=""urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2""
                        xmlns:cbc=""urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2""
                        xmlns:mac=""urn:X-MyCompany:Aggregate"" 
                        xmlns:mbc=""urn:X-MyCompany:Basic"">

          <mac:QualificationLevel>
            <cbc:ID>L1</cbc:ID>
            <cbc:Description>Level 1</cbc:Description>
            <mbc:LevelPrerequisite>Level0</mbc:LevelPrerequisite>
          </mac:QualificationLevel>

          <mac:ThirdPartyBilling>
            <cac:Party>
              <cac:PartyName>
                <cbc:Name>Jane Doe</cbc:Name>
              </cac:PartyName>
            </cac:Party>
          </mac:ThirdPartyBilling>  

        </mec:Additional>")
                    }
                },
                UBLVersionID = "2.1",
                CustomizationID = "urn:X-demo:TransportShipments",
                ProfileID = "urn:X-demo:CoreElement",
                ID = "1234",
                IssueDate = "2010-08-13",
                IssueTime = "15:30:00.0Z",
                Description = new TextType[]
                {
                    new TextType
                    {
                        Value = "En route"
                    }
                },
                Consignment = new ConsignmentType[]
                {
                    new ConsignmentType
                    {
                        ID = "XYZ987",
                        SummaryDescription = new TextType[]
                        {
                            new TextType
                            {
                                Value = "Electronic components"
                            }
                        }
                    }
                },
                TransportEvent = new TransportEventType[]
                {
                    new TransportEventType
                    {
                        CurrentStatus = new StatusType[]
                        {
                            new StatusType
                            {
                                ConditionCode = "31",
                                Description = new TextType[]
                                {
                                    new TextType
                                    {
                                        Value = "En route"
                                    }
                                }
                            }
                        },
                        Contact = new ContactType[]
                        {
                            new ContactType
                            {
                                Name = "John Smith",
                                ElectronicMail = "jsmith@example.com"
                            }
                        }
                    }
                }
            };
            doc.Xmlns = new System.Xml.Serialization.XmlSerializerNamespaces(new[]
            {
                new XmlQualifiedName("cac","urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"),
                new XmlQualifiedName("cbc","urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"),
                new XmlQualifiedName("ext","urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2"),
            });
            return doc;
        }
    }
}
