// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     https://github.com/Gammern/ubllarsen
//     
// </auto-generated>
//------------------------------------------------------------------------------
namespace UblLarsen.Ubl2
{
    using Cac;
    using Udt;
    
    
    /// <summary>
    /// ComponentType: ABIE
    /// <para>DictionaryEntryName: Waybill. Details</para>
    /// <para>Definition: A transport document describing a shipment It is issued by the party who undertakes to provide transportation services, or undertakes to arrange for their provision, to the party who gives instructions for the transportation services (shipper, consignor, etc.). It states the instructions for the beneficiary and may contain the details of the transportation, charges, and terms and conditions under which the transportation service is provided.</para>
    /// <para>ObjectClass: Waybill</para>
    /// <para>AlternativeBusinessTerms: Consignment Note</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.1.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute("Waybill", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:Waybill-2")]
#if USE_UBL_XMLROOTATTRIBUTE
    [System.Xml.Serialization.XmlRootAttribute("Waybill", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:Waybill-2", IsNullable=false)]
#endif
    public partial class WaybillType : UblBaseDocumentType
    {
        
        /// <summary>
        /// ComponentType: BBIE
        /// <para>DictionaryEntryName: Waybill. Carrier Assigned_ Identifier. Identifier</para>
        /// <para>Definition: An identifier (in the form of a reference number) assigned by a carrier or its agent to identify a specific shipment.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Waybill</para>
        /// <para>PropertyTermQualifier: Carrier Assigned</para>
        /// <para>PropertyTerm: Identifier</para>
        /// <para>RepresentationTerm: Identifier</para>
        /// <para>DataType: Identifier. Type</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public IdentifierType CarrierAssignedID { get; set; }
        
        /// <summary>
        /// ComponentType: BBIE
        /// <para>DictionaryEntryName: Waybill. UUID. Identifier</para>
        /// <para>Definition: A universally unique identifier for an instance of this document.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Waybill</para>
        /// <para>PropertyTerm: UUID</para>
        /// <para>RepresentationTerm: Identifier</para>
        /// <para>DataType: Identifier. Type</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public IdentifierType UUID { get; set; }
        
        /// <summary>
        /// ComponentType: BBIE
        /// <para>DictionaryEntryName: Waybill. Issue Date. Date</para>
        /// <para>Definition: The date, assigned by the sender, on which this document was issued.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Waybill</para>
        /// <para>PropertyTerm: Issue Date</para>
        /// <para>RepresentationTerm: Date</para>
        /// <para>DataType: Date. Type</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public DateType IssueDate { get; set; }
        
        /// <summary>
        /// ComponentType: BBIE
        /// <para>DictionaryEntryName: Waybill. Issue Time. Time</para>
        /// <para>Definition: The time, assigned by the sender, at which this document was issued.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Waybill</para>
        /// <para>PropertyTerm: Issue Time</para>
        /// <para>RepresentationTerm: Time</para>
        /// <para>DataType: Time. Type</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public TimeType IssueTime { get; set; }
        
        /// <summary>
        /// ComponentType: BBIE
        /// <para>DictionaryEntryName: Waybill. Name</para>
        /// <para>Definition: Text, assigned by the sender, that identifies this document to business users.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Waybill</para>
        /// <para>PropertyTerm: Name</para>
        /// <para>RepresentationTerm: Name</para>
        /// <para>DataType: Name. Type</para>
        /// <para>Examples: Air Waybill , House Waybill</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public NameType Name { get; set; }
        
        /// <summary>
        /// ComponentType: BBIE
        /// <para>DictionaryEntryName: Waybill. Description. Text</para>
        /// <para>Definition: Text describing the contents of the Waybill.</para>
        /// <para>Cardinality: 0..n</para>
        /// <para>ObjectClass: Waybill</para>
        /// <para>PropertyTerm: Description</para>
        /// <para>RepresentationTerm: Text</para>
        /// <para>DataType: Text. Type</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Description", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public TextType[] Description { get; set; }
        
        /// <summary>
        /// ComponentType: BBIE
        /// <para>DictionaryEntryName: Waybill. Note. Text</para>
        /// <para>Definition: Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.</para>
        /// <para>Cardinality: 0..n</para>
        /// <para>ObjectClass: Waybill</para>
        /// <para>PropertyTerm: Note</para>
        /// <para>RepresentationTerm: Text</para>
        /// <para>DataType: Text. Type</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Note", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public TextType[] Note { get; set; }
        
        /// <summary>
        /// ComponentType: BBIE
        /// <para>DictionaryEntryName: Waybill. Shipping Order Identifier. Identifier</para>
        /// <para>Definition: An identifier (in the form of a reference number) of the Shipping Order or Forwarding Instruction associated with this shipment.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Waybill</para>
        /// <para>PropertyTerm: Shipping Order Identifier</para>
        /// <para>RepresentationTerm: Identifier</para>
        /// <para>DataType: Identifier. Type</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public IdentifierType ShippingOrderID { get; set; }
        
        /// <summary>
        /// ComponentType: BBIE
        /// <para>DictionaryEntryName: Waybill. Ad Valorem_ Indicator. Indicator</para>
        /// <para>Definition: A term used in commerce in reference to certain duties, called ad valorem duties, which are levied on commodities at certain rates per centum on their value.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Waybill</para>
        /// <para>PropertyTermQualifier: Ad Valorem</para>
        /// <para>PropertyTerm: Indicator</para>
        /// <para>RepresentationTerm: Indicator</para>
        /// <para>DataType: Indicator. Type</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public IndicatorType AdValoremIndicator { get; set; }
        
        /// <summary>
        /// ComponentType: BBIE
        /// <para>DictionaryEntryName: Waybill. Declared Carriage_ Value. Amount</para>
        /// <para>Definition: Value declared by the shipper or his agent solely for the purpose of varying the carrier's level of liability from that provided in the contract of carriage in case of loss or damage to goods or delayed delivery.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Waybill</para>
        /// <para>PropertyTermQualifier: Declared Carriage</para>
        /// <para>PropertyTerm: Value</para>
        /// <para>RepresentationTerm: Amount</para>
        /// <para>DataType: Amount. Type</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public AmountType DeclaredCarriageValueAmount { get; set; }
        
        /// <summary>
        /// ComponentType: BBIE
        /// <para>DictionaryEntryName: Waybill. Other_ Instruction. Text</para>
        /// <para>Definition: Other free-text instructions related to the shipment to the forwarders or carriers. This should only be used where such information cannot be represented in other structured information entities within the document.</para>
        /// <para>Cardinality: 0..n</para>
        /// <para>ObjectClass: Waybill</para>
        /// <para>PropertyTermQualifier: Other</para>
        /// <para>PropertyTerm: Instruction</para>
        /// <para>RepresentationTerm: Text</para>
        /// <para>DataType: Text. Type</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OtherInstruction", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public TextType[] OtherInstruction { get; set; }
        
        /// <summary>
        /// ComponentType: ASBIE
        /// <para>DictionaryEntryName: Waybill. Consignor_ Party. Party</para>
        /// <para>Definition: The party consigning goods, as stipulated in the transport contract by the party ordering transport.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Waybill</para>
        /// <para>PropertyTermQualifier: Consignor</para>
        /// <para>PropertyTerm: Party</para>
        /// <para>AssociatedObjectClass: Party</para>
        /// <para>RepresentationTerm: Party</para>
        /// <para>AlternativeBusinessTerms: Consignor (WCO ID 71 and 72)</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public PartyType ConsignorParty { get; set; }
        
        /// <summary>
        /// ComponentType: ASBIE
        /// <para>DictionaryEntryName: Waybill. Carrier_ Party. Party</para>
        /// <para>Definition: The party providing the transport of goods between named points.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Waybill</para>
        /// <para>PropertyTermQualifier: Carrier</para>
        /// <para>PropertyTerm: Party</para>
        /// <para>AssociatedObjectClass: Party</para>
        /// <para>RepresentationTerm: Party</para>
        /// <para>AlternativeBusinessTerms: Transport Company, Shipping Line, NVOCC, Airline, Haulier, Courier, Carrier (WCO ID 49 and 50)</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public PartyType CarrierParty { get; set; }
        
        /// <summary>
        /// ComponentType: ASBIE
        /// <para>DictionaryEntryName: Waybill. Freight Forwarder_ Party. Party</para>
        /// <para>Definition: A party combining individual smaller consignments into a single larger shipment (a so-called consolidated consignment or shipment) that is sent to a counterpart who mirrors the consolidator's activity by dividing the consolidated consignment into its original components.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Waybill</para>
        /// <para>PropertyTermQualifier: Freight Forwarder</para>
        /// <para>PropertyTerm: Party</para>
        /// <para>AssociatedObjectClass: Party</para>
        /// <para>RepresentationTerm: Party</para>
        /// <para>AlternativeBusinessTerms: Consolidator (WCO ID 192 AND 193)</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public PartyType FreightForwarderParty { get; set; }
        
        /// <summary>
        /// ComponentType: ASBIE
        /// <para>DictionaryEntryName: Waybill. Shipment</para>
        /// <para>Definition: A description of the shipment.</para>
        /// <para>Cardinality: 1</para>
        /// <para>ObjectClass: Waybill</para>
        /// <para>PropertyTerm: Shipment</para>
        /// <para>AssociatedObjectClass: Shipment</para>
        /// <para>RepresentationTerm: Shipment</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ShipmentType Shipment { get; set; }
        
        /// <summary>
        /// ComponentType: ASBIE
        /// <para>DictionaryEntryName: Waybill. Document Reference</para>
        /// <para>Definition: A reference to another document associated with this document.</para>
        /// <para>Cardinality: 0..n</para>
        /// <para>ObjectClass: Waybill</para>
        /// <para>PropertyTerm: Document Reference</para>
        /// <para>AssociatedObjectClass: Document Reference</para>
        /// <para>RepresentationTerm: Document Reference</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("DocumentReference", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public DocumentReferenceType[] DocumentReference { get; set; }
        
        /// <summary>
        /// ComponentType: ASBIE
        /// <para>DictionaryEntryName: Waybill. Exchange Rate</para>
        /// <para>Definition: Information about the rate of exchange (conversion) between two currencies.</para>
        /// <para>Cardinality: 0..n</para>
        /// <para>ObjectClass: Waybill</para>
        /// <para>PropertyTerm: Exchange Rate</para>
        /// <para>AssociatedObjectClass: Exchange Rate</para>
        /// <para>RepresentationTerm: Exchange Rate</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ExchangeRate", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ExchangeRateType[] ExchangeRate { get; set; }
        
        /// <summary>
        /// ComponentType: ASBIE
        /// <para>DictionaryEntryName: Waybill. Document Distribution</para>
        /// <para>Definition: A list of interested parties to whom this document is distributed.</para>
        /// <para>Cardinality: 0..n</para>
        /// <para>ObjectClass: Waybill</para>
        /// <para>PropertyTerm: Document Distribution</para>
        /// <para>AssociatedObjectClass: Document Distribution</para>
        /// <para>RepresentationTerm: Document Distribution</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("DocumentDistribution", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public DocumentDistributionType[] DocumentDistribution { get; set; }
        
        /// <summary>
        /// ComponentType: ASBIE
        /// <para>DictionaryEntryName: Waybill. Signature</para>
        /// <para>Definition: A signature applied to this document.</para>
        /// <para>Cardinality: 0..n</para>
        /// <para>ObjectClass: Waybill</para>
        /// <para>PropertyTerm: Signature</para>
        /// <para>AssociatedObjectClass: Signature</para>
        /// <para>RepresentationTerm: Signature</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Signature", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public SignatureType[] Signature { get; set; }
    }
}
