// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     https://github.com/Gammern/ubllarsen
//     
// </auto-generated>
//------------------------------------------------------------------------------
namespace UblLarsen.Ubl2
{
    using Cac;
    using Udt;
    
    
    /// <summary>
    /// ComponentType: ABIE
    /// <para>DictionaryEntryName: Transportation Status. Details</para>
    /// <para>Definition: A document to circulate reports of transportation status or changes in status (events) among a group of participants.</para>
    /// <para>ObjectClass: Transportation Status</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.1.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute("TransportationStatus", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:TransportationStatus-2")]
#if USE_UBL_XMLROOTATTRIBUTE
    [System.Xml.Serialization.XmlRootAttribute("TransportationStatus", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:TransportationStatus-2", IsNullable=false)]
#endif
    public partial class TransportationStatusType : UblBaseDocumentType
    {
        
        /// <summary>
        /// ComponentType: BBIE
        /// <para>DictionaryEntryName: Transportation Status. Carrier Assigned_ Identifier. Identifier</para>
        /// <para>Definition: A reference number assigned by a carrier or its agent to identify a specific shipment, such as a booking reference number when cargo space is reserved prior to loading.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Transportation Status</para>
        /// <para>PropertyTermQualifier: Carrier Assigned</para>
        /// <para>PropertyTerm: Identifier</para>
        /// <para>RepresentationTerm: Identifier</para>
        /// <para>DataType: Identifier. Type</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public IdentifierType CarrierAssignedID { get; set; }
        
        /// <summary>
        /// ComponentType: BBIE
        /// <para>DictionaryEntryName: Transportation Status. UUID. Identifier</para>
        /// <para>Definition: A universally unique identifier for an instance of this document.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Transportation Status</para>
        /// <para>PropertyTerm: UUID</para>
        /// <para>RepresentationTerm: Identifier</para>
        /// <para>DataType: Identifier. Type</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public IdentifierType UUID { get; set; }
        
        /// <summary>
        /// ComponentType: BBIE
        /// <para>DictionaryEntryName: Transportation Status. Issue Date. Date</para>
        /// <para>Definition: The date, assigned by the sender, on which this document was issued.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Transportation Status</para>
        /// <para>PropertyTerm: Issue Date</para>
        /// <para>RepresentationTerm: Date</para>
        /// <para>DataType: Date. Type</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public DateType IssueDate { get; set; }
        
        /// <summary>
        /// ComponentType: BBIE
        /// <para>DictionaryEntryName: Transportation Status. Issue Time. Time</para>
        /// <para>Definition: The time, assigned by the sender, at which this document was issued.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Transportation Status</para>
        /// <para>PropertyTerm: Issue Time</para>
        /// <para>RepresentationTerm: Time</para>
        /// <para>DataType: Time. Type</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public TimeType IssueTime { get; set; }
        
        /// <summary>
        /// ComponentType: BBIE
        /// <para>DictionaryEntryName: Transportation Status. Name</para>
        /// <para>Definition: Text, assigned by the sender, that identifies this document to business users.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Transportation Status</para>
        /// <para>PropertyTerm: Name</para>
        /// <para>RepresentationTerm: Name</para>
        /// <para>DataType: Name. Type</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public NameType Name { get; set; }
        
        /// <summary>
        /// ComponentType: BBIE
        /// <para>DictionaryEntryName: Transportation Status. Description. Text</para>
        /// <para>Definition: A textual description of transportation status.</para>
        /// <para>Cardinality: 0..n</para>
        /// <para>ObjectClass: Transportation Status</para>
        /// <para>PropertyTerm: Description</para>
        /// <para>RepresentationTerm: Text</para>
        /// <para>DataType: Text. Type</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Description", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public TextType[] Description { get; set; }
        
        /// <summary>
        /// ComponentType: BBIE
        /// <para>DictionaryEntryName: Transportation Status. Note. Text</para>
        /// <para>Definition: Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.</para>
        /// <para>Cardinality: 0..n</para>
        /// <para>ObjectClass: Transportation Status</para>
        /// <para>PropertyTerm: Note</para>
        /// <para>RepresentationTerm: Text</para>
        /// <para>DataType: Text. Type</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Note", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public TextType[] Note { get; set; }
        
        /// <summary>
        /// ComponentType: BBIE
        /// <para>DictionaryEntryName: Transportation Status. Shipping Order Identifier. Identifier</para>
        /// <para>Definition: A reference number for a shipping order.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Transportation Status</para>
        /// <para>PropertyTerm: Shipping Order Identifier</para>
        /// <para>RepresentationTerm: Identifier</para>
        /// <para>DataType: Identifier. Type</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public IdentifierType ShippingOrderID { get; set; }
        
        /// <summary>
        /// ComponentType: BBIE
        /// <para>DictionaryEntryName: Transportation Status. Other_ Instruction. Text</para>
        /// <para>Definition: An instruction regarding this message.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Transportation Status</para>
        /// <para>PropertyTermQualifier: Other</para>
        /// <para>PropertyTerm: Instruction</para>
        /// <para>RepresentationTerm: Text</para>
        /// <para>DataType: Text. Type</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public TextType OtherInstruction { get; set; }
        
        /// <summary>
        /// ComponentType: BBIE
        /// <para>DictionaryEntryName: Transportation Status. Transportation Status Type Code. Code</para>
        /// <para>Definition: A code signifying the type of status provided in a Transportation Status document.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Transportation Status</para>
        /// <para>PropertyTerm: Transportation Status Type Code</para>
        /// <para>RepresentationTerm: Code</para>
        /// <para>DataType: Code. Type</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public CodeType TransportationStatusTypeCode { get; set; }
        
        /// <summary>
        /// ComponentType: BBIE
        /// <para>DictionaryEntryName: Transportation Status. Transport Execution Status Code. Code</para>
        /// <para>Definition: A code signifying the overall status of transport service execution.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Transportation Status</para>
        /// <para>PropertyTerm: Transport Execution Status Code</para>
        /// <para>RepresentationTerm: Code</para>
        /// <para>DataType: Code. Type</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public CodeType TransportExecutionStatusCode { get; set; }
        
        /// <summary>
        /// ComponentType: ASBIE
        /// <para>DictionaryEntryName: Transportation Status. Consignment</para>
        /// <para>Definition: A consignment associated with this Transportation Status report.</para>
        /// <para>Cardinality: 0..n</para>
        /// <para>ObjectClass: Transportation Status</para>
        /// <para>PropertyTerm: Consignment</para>
        /// <para>AssociatedObjectClass: Consignment</para>
        /// <para>RepresentationTerm: Consignment</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Consignment", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ConsignmentType[] Consignment { get; set; }
        
        /// <summary>
        /// ComponentType: ASBIE
        /// <para>DictionaryEntryName: Transportation Status. Transport Event</para>
        /// <para>Definition: An event associated with this Transportation Status report.</para>
        /// <para>Cardinality: 0..n</para>
        /// <para>ObjectClass: Transportation Status</para>
        /// <para>PropertyTerm: Transport Event</para>
        /// <para>AssociatedObjectClass: Transport Event</para>
        /// <para>RepresentationTerm: Transport Event</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("TransportEvent", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public TransportEventType[] TransportEvent { get; set; }
        
        /// <summary>
        /// ComponentType: ASBIE
        /// <para>DictionaryEntryName: Transportation Status. Document Reference</para>
        /// <para>Definition: A reference to another document associated with this document.</para>
        /// <para>Cardinality: 0..n</para>
        /// <para>ObjectClass: Transportation Status</para>
        /// <para>PropertyTerm: Document Reference</para>
        /// <para>AssociatedObjectClass: Document Reference</para>
        /// <para>RepresentationTerm: Document Reference</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("DocumentReference", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public DocumentReferenceType[] DocumentReference { get; set; }
        
        /// <summary>
        /// ComponentType: ASBIE
        /// <para>DictionaryEntryName: Transportation Status. Signature</para>
        /// <para>Definition: A signature applied to this document.</para>
        /// <para>Cardinality: 0..n</para>
        /// <para>ObjectClass: Transportation Status</para>
        /// <para>PropertyTerm: Signature</para>
        /// <para>AssociatedObjectClass: Signature</para>
        /// <para>RepresentationTerm: Signature</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Signature", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public SignatureType[] Signature { get; set; }
        
        /// <summary>
        /// ComponentType: ASBIE
        /// <para>DictionaryEntryName: Transportation Status. Sender_ Party. Party</para>
        /// <para>Definition: The party sending this Transportation Status report.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Transportation Status</para>
        /// <para>PropertyTermQualifier: Sender</para>
        /// <para>PropertyTerm: Party</para>
        /// <para>AssociatedObjectClass: Party</para>
        /// <para>RepresentationTerm: Party</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public PartyType SenderParty { get; set; }
        
        /// <summary>
        /// ComponentType: ASBIE
        /// <para>DictionaryEntryName: Transportation Status. Receiver_ Party. Party</para>
        /// <para>Definition: The party receiving this Transportation Status report.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Transportation Status</para>
        /// <para>PropertyTermQualifier: Receiver</para>
        /// <para>PropertyTerm: Party</para>
        /// <para>AssociatedObjectClass: Party</para>
        /// <para>RepresentationTerm: Party</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public PartyType ReceiverParty { get; set; }
        
        /// <summary>
        /// ComponentType: ASBIE
        /// <para>DictionaryEntryName: Transportation Status. Transportation Status Request_ Document Reference. Document Reference</para>
        /// <para>Definition: A reference to the Transportation Status Request to which this report is a response.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Transportation Status</para>
        /// <para>PropertyTermQualifier: Transportation Status Request</para>
        /// <para>PropertyTerm: Document Reference</para>
        /// <para>AssociatedObjectClass: Document Reference</para>
        /// <para>RepresentationTerm: Document Reference</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public DocumentReferenceType TransportationStatusRequestDocumentReference { get; set; }
        
        /// <summary>
        /// ComponentType: ASBIE
        /// <para>DictionaryEntryName: Transportation Status. Transport Execution Plan_ Document Reference. Document Reference</para>
        /// <para>Definition: A reference to the Transport Execution Plan associated with the transport service whose status is being reported.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Transportation Status</para>
        /// <para>PropertyTermQualifier: Transport Execution Plan</para>
        /// <para>PropertyTerm: Document Reference</para>
        /// <para>AssociatedObjectClass: Document Reference</para>
        /// <para>RepresentationTerm: Document Reference</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public DocumentReferenceType TransportExecutionPlanDocumentReference { get; set; }
        
        /// <summary>
        /// ComponentType: ASBIE
        /// <para>DictionaryEntryName: Transportation Status. Updated Pickup_ Transport Event. Transport Event</para>
        /// <para>Definition: Update of the original plan regarding a pickup of goods.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Transportation Status</para>
        /// <para>PropertyTermQualifier: Updated Pickup</para>
        /// <para>PropertyTerm: Transport Event</para>
        /// <para>AssociatedObjectClass: Transport Event</para>
        /// <para>RepresentationTerm: Transport Event</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public TransportEventType UpdatedPickupTransportEvent { get; set; }
        
        /// <summary>
        /// ComponentType: ASBIE
        /// <para>DictionaryEntryName: Transportation Status. Updated Delivery_ Transport Event. Transport Event</para>
        /// <para>Definition: Update of the original plan regarding a delivery.</para>
        /// <para>Cardinality: 0..1</para>
        /// <para>ObjectClass: Transportation Status</para>
        /// <para>PropertyTermQualifier: Updated Delivery</para>
        /// <para>PropertyTerm: Transport Event</para>
        /// <para>AssociatedObjectClass: Transport Event</para>
        /// <para>RepresentationTerm: Transport Event</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public TransportEventType UpdatedDeliveryTransportEvent { get; set; }
        
        /// <summary>
        /// ComponentType: ASBIE
        /// <para>DictionaryEntryName: Transportation Status. Status_ Location. Location</para>
        /// <para>Definition: Locations associated with this Transportation Status report.</para>
        /// <para>Cardinality: 0..n</para>
        /// <para>ObjectClass: Transportation Status</para>
        /// <para>PropertyTermQualifier: Status</para>
        /// <para>PropertyTerm: Location</para>
        /// <para>AssociatedObjectClass: Location</para>
        /// <para>RepresentationTerm: Location</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("StatusLocation", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public LocationType[] StatusLocation { get; set; }
        
        /// <summary>
        /// ComponentType: ASBIE
        /// <para>DictionaryEntryName: Transportation Status. Status_ Period. Period</para>
        /// <para>Definition: A period for which status is provided.</para>
        /// <para>Cardinality: 0..n</para>
        /// <para>ObjectClass: Transportation Status</para>
        /// <para>PropertyTermQualifier: Status</para>
        /// <para>PropertyTerm: Period</para>
        /// <para>AssociatedObjectClass: Period</para>
        /// <para>RepresentationTerm: Period</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("StatusPeriod", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public PeriodType[] StatusPeriod { get; set; }
    }
}
